# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb9d0e41ec434486b6d668b9057ef78735c7fcaf599d053e55aeab49b1f2f6111e7a5d3cd427c865fd94d5d0aee6600bc5cfad325bc606762bb4c1a8bb0bc87c

test:
  secret_key_base: 25c34662c82fa1776f3f60a82da4ce36cb8f98832ef56197f79a866871655809050f941db8acb4774fbbc6b2a56b5f6f0eef11a69fa95ae07142fd29712851b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
